local colDesc, colCmd = '\255\255\255\125', '\255\255\100\50'
local widgetDesc = table.concat({
	' ',
	colDesc..'		  <Map '.. Game.mapName..'>',
	' ',
	colDesc..'- Allow to keep Advanced Map Shading Mode and remove/reduce map shadings selectively.',
	colDesc..'Advanced Map Shading can be switched through command '..colCmd..'/AdvMapShading'..colDesc..' (ON by default)',
	colDesc..'This mode is needed to be able to draw custom Decals among other things.',
	' ',
	colDesc..'- Allow to reduce ground texture definition or color it in a plain color',
	' ',
	colDesc..'commands:',
	colCmd..'	/smf options		'..colDesc..'open options',
	colCmd..'	/smf reduce	[0-100] '..colDesc..'reduce all the map shading to scale (n percent can be specified)',
	colCmd..'	/smf disable		'..colDesc..'disable all',
	colCmd..'	/smf original		'..colDesc..'revert all',
	colCmd..'	/groundtex options	'..colDesc..'open options',
	colCmd..'	/groundtex reduce	[0-100] '..colDesc..'reduce ground texture definition to global scale (n percent can be specified)',
	colCmd..'	/groundtex unicolor [r,g,b] '..colDesc..'replace ground textures by simple color (r,g,b can be specified)',
	colCmd..'	/groundtex original	'..colDesc..'revert to original ground',
}, '\n')

function widget:GetInfo()
	return {
		name      = "Map Shading Hax",
		desc      = '\255\255\255\0'..'Tweak Map Shadings and Ground Texture\n' .. widgetDesc,
		author    = "Helwor",
		date      = "Apr 2026",
		license   = "GNU GPL, v2 or later",
		-- layer     = 2, -- after Unit Start State
		layer     = -99999990,
		enabled   = true,  --  loaded by default?
		-- api       = true,
		handler   = true,
	}
end
local Echo = Spring.Echo
-- Spring.SetMapRenderingParams({ -- STUDY
--     splatTexScales = {0, 0, 0, 0},
--     splatTexMults  = {0, 0, 0, 0},
--     splatDetailNormalDiffuseAlpha = false,
--     voidGround = true,
-- })
local mapShadingTextures = {
	"$ssmf_specular",
	"$ssmf_normals",
	"$ssmf_splat_detail",
	"$ssmf_splat_normals:0",
	"$ssmf_splat_normals:1",
	"$ssmf_splat_normals:2",
	"$ssmf_splat_normals:3",
	"$ssmf_splat_distr",
	"$ssmf_emission",
	"$ssmf_parallax",
	"$ssmf_sky_refl",
}

local NEUTER_NORMAL_R = 0.5
local NEUTER_NORMAL_G = 0.5
local NEUTER_NORMAL_B = 1
local NEUTER_NORMAL_A = 0.5


local NEUTER_DETAIL_R = 0.5
local NEUTER_DETAIL_G = 0.5
local NEUTER_DETAIL_B = 0.5
local NEUTER_DETAIL_A = 1

local NEUTER_SKYREFL_R = 0
local NEUTER_SKYREFL_G = 0
local NEUTER_SKYREFL_B = 0
local NEUTER_SKYREFL_A = 1

local byName = {}
for _, name in pairs(mapShadingTextures) do
	byName[name] = true
end

-- Variables
----------
----
local bigSquareSize = 128 -- constant?
local bigTexSize = 8 * bigSquareSize
local groundCellsX = math.ceil(Game.mapSizeX / bigTexSize)
local groundCellsY = math.ceil(Game.mapSizeZ / bigTexSize)
local autoGenerated = Spring.GetGameRulesParam("mapgen_enabled")
local needSaveOriGround = false and autoGenerated -- FIXME Can't save current generated texture!
local ground_def = false
local oriGround = {}
local groundTexs = {}
---- 
local updateSMF = {}
local currentSMFs = {}
local scale = 0.5
local ground_scale = 0.5
----
local mapName = Game.mapName
local update_rate = 2
local initialized = false
----
options = {}
local options = options
options_path = 'Tweakings/' .. widget.GetInfo().name
options_order = {
	'description',
	'space',
	'ground_label',
	'space',
	'ground_def-'..mapName,
	'ground_scale-'..mapName,
	'ground_color-'..mapName,

	'space',
	'smf_label',
	'space',
	'find_rgba', -- for debugging
	'smf_all',
	'smf_scale',
	'space',
	-- per texture smf options added later
}

-- Tex Formats
--------
local fmt_disable = {
	target = GL.TEXTURE_2D,
	format = GL.RGBA4,
	min_filter = GL.LINEAR_MIPMAP_LINEAR,
	mag_filter = GL.LINEAR,
	wrap_s = GL.CLAMP_TO_EDGE,
	wrap_t = GL.CLAMP_TO_EDGE,
	fbo = true,
}


local fmt_mipmap = {
	target = GL.TEXTURE_2D,
	format = GL.RGBA8,
	min_filter = GL.LINEAR_MIPMAP_LINEAR,
	mag_filter = GL.LINEAR,
	wrap_s = GL.CLAMP_TO_EDGE,
	wrap_t = GL.CLAMP_TO_EDGE,
	fbo = true,
}

local fmt_mipmapSMF = {
	target = GL.TEXTURE_2D,
	format = GL.RGBA4,
	min_filter = GL.LINEAR_MIPMAP_LINEAR,
	mag_filter = GL.LINEAR,
	wrap_s = GL.CLAMP_TO_EDGE,
	wrap_t = GL.CLAMP_TO_EDGE,
	fbo = true,
}

local fmt_mipmapNormalsBig = {
	target = GL.TEXTURE_2D,
	format = GL.RGB8,
	min_filter = GL.LINEAR_MIPMAP_LINEAR,
	mag_filter = GL.LINEAR,
	wrap_s = GL.CLAMP_TO_EDGE,
	wrap_t = GL.CLAMP_TO_EDGE,
	-- lodBias = 1,
	fbo = true,
}

local fmt_mipmapNormals = {
	target = GL.TEXTURE_2D,
	format = GL.RGBA4,
	min_filter = GL.LINEAR_MIPMAP_LINEAR,
	mag_filter = GL.LINEAR,
	wrap_s = GL.REPEAT,
	wrap_t = GL.REPEAT,
	fbo = true,
}

local fmt_groundGet = {
    target = GL.TEXTURE_2D,
    format = GL.RGBA8,
    min_filter = GL.LINEAR,
    mag_filter = GL.LINEAR,
	wrap_s = GL.CLAMP_TO_EDGE,
	wrap_t = GL.CLAMP_TO_EDGE,
}

-- OPTIONS
-----------------------
options.space = {
	type = 'label',
	name = '',
}
options.description = {
	type = 'text',
	name = 'Tweak Map Shadings and Ground Texture',
	value = widgetDesc,
}

options.ground_label = {
	type = 'label',
	name = '--- GROUND DEF' .. (autoGenerated and ' (Unavailable with autogen map)' or ''),
}

options['ground_def-'..mapName] = {
	name = 'Reduce/Paint ground' .. (autoGenerated and ' (Unavailable with autogen map)' or ''),
	desc = 'For the luls it doesn\'t really help FPS',
	type = 'radioButton',
	items = {
		{key = 'original', name = 'Original'},
		{key = 'unicolor', name = 'Color Ground'},
		{key = 'reduce', name = 'Reduce to scale'},
	},
	value = 'original',
	OnChange = function(self)
		if autoGenerated then
			Echo(self.name)
			return
		end
		ground_def = self.value
	end,
	noHotkey = true,
}

options['ground_scale-' .. mapName] = {
	name = '  Ground Scale' .. (autoGenerated and ' (Unavailable with autogen map)' or ''),
	type = 'number',
	value = ground_scale,
	min = 0, step = 0.01, max = 1,
	OnChange = function(self)
		if autoGenerated then
			Echo(self.name)
			return
		end
		ground_scale = self.value
		local defOpt = options['ground_def-'..mapName]
		if defOpt.value == 'reduce' then
			defOpt:OnChange()
		end
	end,
	tooltipFunction = function(self)
		return (self.value * 100) .. '%'
	end,
}
options['ground_color-' .. mapName] = {
	name = 'Ground Uni Color' .. (autoGenerated and ' (Unavailable with autogen map)' or ''),
	type = 'colors',
	value = {0.5,0.5,0.5,1},
	-- update_on_the_fly = true,
	OnChange = function(self)
		if autoGenerated then
			Echo(self.name)
			return
		end
		if options['ground_def-'..mapName].value == 'unicolor' then
			ground_def = 'unicolor'
		end
	end,
}
options_order[#options_order+1] = 'space'

options.smf_label = {
	type = 'label',
	name = '--- MAP SHADING DEF',
}


options.smf_all = {
	name = 'Apply to All',
	type = 'list',
	items = {
		{key = 'original', name = 'Original'},
		{key = 'disable', name = 'Disable'},
		{key = 'reduce', name = 'Reduce'},
	},
	value = 'original',
	OnChange = function(self)
		if initialized then
			local value = self.value
			for i, namedTex in pairs(mapShadingTextures) do
				local shortNamed = namedTex:gsub('$ssmf_', '')
				local defOpt = options[shortNamed..'-'..mapName]
				if defOpt and defOpt.value ~= value then
					defOpt.value = value
					defOpt:OnChange()
				end
			end
		end
	end,
	reset = true
	-- noSave = true,
}

options.smf_scale = {
	name = 'Global Scale',
	desc = 'Set scale for every SMF texture',
	type = 'number',
	value = scale,
	min = 0, step = 0.01, max = 1,
	OnChange = function(self)
		scale = self.value
		if initialized then
			for i, namedTex in pairs(mapShadingTextures) do
				local shortNamed = namedTex:gsub('$ssmf_', '')
				local customScaleOpt = options[shortNamed..'-'..mapName..'_scale']
				if customScaleOpt and customScaleOpt.value ~= scale then
					customScaleOpt.value = scale
					customScaleOpt:OnChange()
				end
			end
		end
	end,
	tooltipFunction = function(self)
		return (self.value * 100) .. '%'
	end,
	reset = true,
}

options.find_rgba = { -- for debugging, deactivated
	name = 'Find RGBA',
	type = 'colors',
	value = {0,0,0,0},
	-- update_on_the_fly = true,
	OnChange = function(self)
		-- for name_opt, opt in pairs(options) do
		-- 	if byName['$ssmf_'..name_opt:gsub('%-.*$', '')] then
		-- 		if opt.value == 'reduce' then
		-- 			opt:OnChange()
		-- 		end
		-- 	end
		-- end
	end,
	reset = true,
	hidden = true,
}

local function CreateSMFOption(namedTex, info)
	local shortNamed = namedTex:gsub('$ssmf_', '')
	local name = shortNamed .. '-'..mapName
	local humanName = shortNamed:sub(1,1):upper() .. shortNamed:sub(2)
	options[name] = {
		name = humanName .. ' ('..info.xsize..'x'..info.ysize..')',
		desc = 'Disable or Reduce Texture to Scale',
		type = 'radioButton',
		items = {
			{key = 'original', name = 'Original'},
			{key = 'disable', name = 'Disable'},
			{key = 'reduce', name = 'Reduce'},
		},
		value = 'original',
		OnChange = function(self)
			updateSMF[namedTex] = self.value
		end,
		noHotkey = true,
	}
	options[name..'_scale'] = {
		name = '  Scale',
		type = 'number',
		value = scale,
		min = 0, step = 0.01, max = 1,
		OnChange = function(self)
			if options[name].value == 'reduce' then
				updateSMF[namedTex] = 'reduce'
			end
		end,
		tooltipFunction = function(self)
			return string.format('%.0f%%', self.value*100)
		end,
		noHotkey = true,
	}
	options_order[#options_order+1] = name
	options_order[#options_order+1] = name..'_scale'
	options_order[#options_order+1] = 'space'

end

for i, namedTex in ipairs(mapShadingTextures) do
	local info = gl.TextureInfo(namedTex)
	if info and (info.xsize or 0) > 1 and (info.ysize or 0) > 1 then
		CreateSMFOption(namedTex, info)
	end
end

local function SetOptionCommands()
	widgetHandler.actionHandler:AddAction(
		widget,
		'smf',
		function(cmd, paramStr, params)
			local param = params[1]
			if param == "options" then
				if WG.crude.OpenWidgetOptions then
					WG.crude.OpenWidgetOptions(widget)
				else
					WG.crude.OpenPath(options_path)
				end
			elseif param == 'reduce' then
				if params[2] then
					local scale = tonumber(params[2])
					if not scale then
						Echo('Wrong scale param '..tostring(params[2])..' for command /smf reduce [scale], value must be anumber (0-100)')
						return
					end
					scale = math.min(math.floor(scale + 0.5), 100) / 100
					local scaleOpt = options.smf_scale
					scaleOpt.value = scale
					scaleOpt:OnChange()
				end
				if options.smf_all.value ~= param then
					options.smf_all.value = param
					options.smf_all:OnChange()
				end
			elseif param == 'original' or param == 'disable' then
				options.smf_all.value = param
				options.smf_all:OnChange()
			else
				Echo('/smf unrecognized command param ' .. tostring(param) .. ', valids are "options", "original", "reduce", "disable"')
			end
		end,
		nil,
		't'
	)
	widgetHandler.actionHandler:AddAction(
		widget,
		'groundtex',
		function(cmd, paramStr, params) --
			if autoGenerated then
				Echo('/groundtex command unavailable with autogen maps')
				return
			end
			local colorOpt = options['ground_color-'..mapName]
			local defOpt = options['ground_def-'..mapName]
			local param = params[1]
			if param == 'options' then
				if WG.crude.OpenWidgetOptions then
					WG.crude.OpenWidgetOptions(widget)
				else
					WG.crude.OpenPath(options_path)
				end
			elseif param == 'unicolor' then
				if params[2] then
					local color = {}
					for i = 2, 4 do
						local col = tonumber(params[i])
						if not col or col < 0 or col > 1 then
							Echo('Wrong color param #'..i..' for command /groundtex unicolor [r g b], value must be between 0 and 1')
							return
						end
						color[i-1] = col
					end
					for i, c in ipairs(color) do
						colorOpt.value[i] = c
					end
					colorOpt:OnChange()
				end
				if defOpt.value ~= 'unicolor' then
					defOpt.value = 'unicolor'
					defOpt:OnChange()
				end
			elseif param == 'reduce' then
				if params[2] then
					local scale = tonumber(params[2])
					if not scale then
						Echo('Wrong scale param '..tostring(params[2])..' for command /groundtex reduce [scale], value must be anumber (0-100)')
						return
					end
					scale = math.min(math.floor(scale + 0.5), 100) / 100
					local scaleOpt = options['ground_scale-'..mapName]
					if scaleOpt.value ~= scale then
						scaleOpt.value = scale
						scaleOpt:OnChange()
					end
				end
				local defOpt = options['ground_def-'..mapName]
				if defOpt.value ~= 'reduce' then
					defOpt.value = 'reduce'
					defOpt:OnChange()
				end
			elseif param == 'original' then
				if defOpt.value ~= 'original' then
					defOpt.value = 'original'
					defOpt:OnChange()
				end
			else
				Echo('/groundtex unrecognized command param ' .. tostring(param) .. ', valids are "options", "original", "reduce", "unicolor [r,g,b]"')
			end
		end,
		nil,
		't'
	)
end


-- HELPERS
-----------

local function ReduceTexture(tex, scale, yReverse, format, noBlending, R,G,B,A) -- some textures, like splat_distr doesn't give the same result if copied at 100% size. format problem probably
	local info = gl.TextureInfo(tex)

	if not info or info.xsize == 0 or info.ysize == 0 then
		Echo('INVALID TEXTURE', tex, 'info', info, 'size', info and info.xsize, info and info.ysize)
		return nil
	end

	local newW = math.max(1, math.floor(info.xsize * scale))
	local newH = math.max(1, math.floor(info.ysize * scale))
	
	local newTex = gl.CreateTexture(newW, newH, format or fmt_mipmap)
	
	if not newTex then
		Spring.Echo("(ReduceTexture) TEXTURE " .. tex .. " CREATION FAILED")
		return nil
	end
	gl.RenderToTexture(newTex, function()
		gl.Clear(GL.COLOR_BUFFER_BIT, 0,0,0,0)
		if noBlending then
			gl.Blending(false)
		end
		gl.Texture(0, tex)
		if yReverse then
			gl.TexRect(-1, 1, 1, -1)
		else
			gl.TexRect(-1, -1, 1, 1)
		end
		gl.Texture(0, false)
		if noBlending then
			gl.Blending(GL.SRC_ALPHA, GL.ONE_MINUS_SRC_ALPHA)
		end
	end)
	gl.GenerateMipmap(newTex)
	gl.DeleteTextureFBO(newTex) 
	return newTex
end


-- GROUND
-----------

local function SaveOriGround()
	setmetatable(oriGround, {__index = function(self, col) local row = {} rawset(self, col, row) return row end })
	local success = true
	for x = 0, groundCellsX - 1 do
		for y = 0, groundCellsY - 1 do
			local oriTex = gl.CreateTexture(bigTexSize, bigTexSize, fmt_groundGet)
			local _success = Spring.GetMapSquareTexture(x, y, 0, oriTex)
			if _success then
				oriGround[x][y] = oriTex
			else
				Echo('(SaveOriGround) FAILED sampling Ground Texture !')
			end
			success = success and _success
		end
	end
	Echo('Saving Original Ground ' .. (success and 'success' or 'FAILED!'))
	setmetatable(oriGround, nil)
end
local function RevertGround()

	if next(groundTexs) or uniTex then
		for tex in pairs(groundTexs) do
			gl.DeleteTexture(tex)
		end
		if uniTex then
			gl.DeleteTextureFBO(uniTex)
			gl.DeleteTexture(uniTex)
			uniTex = nil
		end
		for x = 0, groundCellsX - 1 do
			for y = 0, groundCellsY - 1 do
				Spring.SetMapSquareTexture(x, y, oriGround[x] and oriGround[x][y] or '')
				-- when restoring or if error, it report false in both case, we can't check for success in that case
			end
		end
		Echo('Reverted Ground Textures ')
	end
end

local function UniGround()
	local r, g, b = unpack(options['ground_color-'..mapName].value)
	if not uniTex then
		uniTex = gl.CreateTexture(1, 1, fmt_mipmap)
	end
	gl.RenderToTexture(uniTex, function()
		gl.Color(r, g, b, 1)
		gl.Rect(-1, -1, 1, 1)
	end)
	
	gl.GenerateMipmap(uniTex)
	local success = true
	for x = 0, groundCellsX - 1 do
		for y = 0, groundCellsY - 1 do
			success = Spring.SetMapSquareTexture(x, y, uniTex) and success
		end
	end
	Echo('Painting Ground ' .. (success and 'success' or 'FAILED!'))
end

local function ReduceGroundDefinition() -- this work but doesnt help FPS really
	RevertGround()
	local success = true
	for x = 0, groundCellsX - 1 do
		for y = 0, groundCellsY - 1 do
			local tmpTex = gl.CreateTexture(bigTexSize, bigTexSize, fmt_groundGet)
			-- local info = gl.TextureInfo(tmpTex)
			local _success = Spring.GetMapSquareTexture(x, y, 0, tmpTex)
			-- Echo("success is ", _success, 'tex info', info.id, info.xsize, info.ysize)
			if _success then
				local rtex = ReduceTexture(tmpTex, ground_scale, true)
				if rtex then
					Spring.SetMapSquareTexture(x, y, rtex)
					groundTexs[rtex] = true
				else
					_success = false
				end

			end
			success = success and _success
			gl.DeleteTexture(tmpTex)
		end
	end
	Echo('Reducing Ground Definition ' .. (ground_scale * 100)..'% '.. (success and 'success' or 'FAILED!'))
end


-- SHADING
-------------

local function GetBaseColor(namedTex)
	return 0,0,0,0
end

local function GetNeuterColor(namedTex)
	if namedTex:find('normals') then
		return NEUTER_NORMAL_R, NEUTER_NORMAL_G, NEUTER_NORMAL_B, NEUTER_NORMAL_A
	elseif namedTex:find('detail') then
		return NEUTER_DETAIL_R, NEUTER_DETAIL_G, NEUTER_DETAIL_B, NEUTER_DETAIL_A
	elseif namedTex:find('sky_refl') then
		return NEUTER_SKYREFL_R, NEUTER_SKYREFL_G, NEUTER_SKYREFL_B, NEUTER_SKYREFL_A
	end
end

local function GetNoBlending(namedTex)
	if namedTex:find('specular') or namedTex:find('normals') or namedTex:find('distr') or namedTex:find('detail') or namedTex:find('sky_refl') then
		return true
	end
end

local function GetFormat(namedTex)
	if namedTex:find('splat_normals') or namedTex:find('detail') then
		return fmt_mipmapNormals
	elseif namedTex:find('ssmf_normals') then
		return fmt_mipmapNormalsBig
	end
	return fmt_mipmapSMF
end

local function ReduceShadingTexture(namedTex, scale, comment)
	comment = comment or ''
	local main, sub = namedTex:gsub(':?%d*',''), tonumber(namedTex:match(':(%d+)$'))
	if currentSMFs[namedTex] then
		gl.DeleteTexture(currentSMFs[namedTex])
		currentSMFs[namedTex] = nil
	end
	Spring.SetMapShadingTexture(main, '', sub) 
	local rtex = ReduceTexture(namedTex, scale, true, GetFormat(namedTex), GetNoBlending(namedTex), GetBaseColor(namedTex))
	if not rtex then
		Echo('Texturing Failed', namedTex)
	else
		gl.GenerateMipmap(rtex)
		Echo('Reduce Shading ' .. comment .. ' ' .. namedTex .. ' ' .. (scale * 100)..'%', Spring.SetMapShadingTexture(main, rtex, sub) and 'success' or 'FAILED')
		currentSMFs[namedTex] = rtex
	end
end

local function DisableShadingTexture(namedTex, comment)
	comment = comment or ''
	local main, sub = namedTex:gsub(':?%d*',''), tonumber(namedTex:match(':(%d+)$'))
	if currentSMFs[namedTex] then
		gl.DeleteTexture(currentSMFs[namedTex])
		currentSMFs[namedTex] = nil
	end
	-- Spring.SetMapShadingTexture(main, '', sub)
	local rtex = gl.CreateTexture(1, 1, fmt_disable)
	gl.RenderToTexture(rtex, function()
		gl.Clear(GL.COLOR_BUFFER_BIT, GetNeuterColor(namedTex))
	end)
	gl.DeleteTextureFBO(rtex)
	gl.GenerateMipmap(rtex)
	if not rtex then
		Echo('No Shading Texture', namedTex)
	else
		Echo('Disable Shading ' .. comment .. ' ' .. namedTex, Spring.SetMapShadingTexture(main, rtex, sub) and 'success' or 'FAILED!')
		currentSMFs[namedTex] = rtex
	end
end

local function RevertShadingTexture(namedTex, comment)
	if currentSMFs[namedTex] then
		gl.DeleteTexture(currentSMFs[namedTex])
		currentSMFs[namedTex] = nil
		comment = comment or ''
		local main, sub = namedTex:gsub(':?%d*',''), tonumber(namedTex:match(':(%d+)$'))
		Echo('Revert Shading ' .. comment .. ' ' .. namedTex, Spring.SetMapShadingTexture(main, '', sub) and 'success' or 'FAILED!')
	end
end

local function RevertAllMapShadings()
	for name_opt, opt in pairs(options) do
		if byName['$ssmf_'..name_opt:gsub('%-.*$', '')] then
			RevertShadingTexture('$ssmf_'..name_opt:gsub('%-.*$', ''))
		end
	end
end	




------- CALL INS
local t = 0
function widget:DrawWorldPreUnit()
	t = t + 1
	if t < 150 then
		return
	end

	initialized = true
	if t%update_rate ~= 0 then
		return
	end
	if ground_def then
		if needSaveOriGround then
			SaveOriGround()
			needSaveOriGround = false
		end
		if ground_def == 'reduce' then
			ReduceGroundDefinition()
		elseif ground_def == 'unicolor' then
			UniGround()
		elseif ground_def == 'original' then
			RevertGround()
		end
		ground_def = false
		return
	end
	if next(updateSMF) then
		for _, namedTex in ipairs(mapShadingTextures) do
			local param = updateSMF[namedTex]
			if param then
				if param == 'reduce' then
					local scale = options[namedTex:gsub('$ssmf_', '') .. '-'..mapName..'_scale'].value
					ReduceShadingTexture(namedTex, scale)
				elseif param == 'disable' then
					DisableShadingTexture(namedTex)
				elseif param == 'original' then
					RevertShadingTexture(namedTex)
				end
				updateSMF[namedTex] = nil
				break
			end
		end
	end
end

function widget:Initialize()
	SetOptionCommands()
end

function widget:Shutdown()
	RevertAllMapShadings()
	RevertGround()

	for namedTex, tex in pairs(currentSMFs) do
		gl.DeleteTexture(rtex)
	end
	for x, col in pairs(oriGround) do
		for y, oriTex in pairs(col) do
			gl.DeleteTexture(oriTex)
		end
	end
	for tex in pairs(groundTexs) do
		gl.DeleteTexture(tex)
	end
	if uniTex then
		gl.DeleteTextureFBO(uniTex)
		gl.DeleteTexture(uniTex)
	end
	widgetHandler.actionHandler:RemoveAction(widget, 'smf')
	widgetHandler.actionHandler:RemoveAction(widget, 'groundtex')
end

--
if f then
	f.DebugWidget(widget)
end

